#!/bin/bash


set -euo pipefail

check_java_version(){
	if !command java -version &>/dev/null;
	then
		echo "java is not installed"
	else
		echo "java is installed with the version"
		java -version
	fi
}

main(){
	check_java_version
}

main "@"
